# Generated by Django 5.0.2 on 2024-02-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_singup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
