# Generated by Django 5.0.2 on 2024-02-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_singup', '0002_alter_users_age_alter_users_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_table',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
