# Generated by Django 5.0.2 on 2024-02-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_singup', '0003_users_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
